
YAAPT_CHANNEL_NONE = 0x00,
YAAPT_CHANNEL_LOG = 'L',
YAAPT_CHANNEL_PLOT = 'P',
YAAPT_CHANNEL_RAW = 'R',
YAAPT_CHANNEL_COMMAND = 'C',
YAAPT_CHANNEL_DATA = 'D'
YAAPT_INIT_START = 0xF0
YAAPT_VERSION = 'V'
YAAPT_CHANNEL_DESC_START = 0x01
YAAPT_CHANNEL_TYPE = 0x02
YAAPT_CHANNEL_NAME = 0x03
YAAPT_CHANNEL_CONTENT_START = 0x04
YAAPT_CHANNEL_CONTENT_END = 0x05
YAAPT_CHANNEL_DESC_END = 0x0E
YAAPT_INIT_END = 0x0F
YAAPT_STRING = 'S'
YAAPT_FLOAT = 'F'
YAAPT_DOUBLE = 'D'
YAAPT_UINT8_T = '8'
YAAPT_INT8_T = '7'
YAAPT_UINT32_T = 'U'
YAAPT_INT32_T = 'S'
YAAPT_STARTSTRING = b'YaaptStart'

YAAPT_SERIAL_BAUD = 115200
